# Generated by Django 6.0.3 on 2026-03-12 20:27

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.upload_img),
        ),
    ]
