# Generated by Django 6.0.3 on 2026-03-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_order_email_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='babyseat',
            field=models.BooleanField(default=1, verbose_name='Добавить детское кресло'),
            preserve_default=False,
        ),
    ]
