# Generated by Django 6.0.3 on 2026-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_order_babyseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_adress',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
