# Generated by Django 6.0.3 on 2026-03-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_order_delivery_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='babyseat',
            field=models.BooleanField(default=False, verbose_name='Добавить детское кресло'),
        ),
    ]
